import {
  BUTTON_COLORS,
  CAROUSEL_COLORS,
  CHECKBOX_COLORS,
  DATE_PICKER_COLORS,
  FORM_COLORS,
  INPUT_COLORS,
  NOTIFICATION_COLORS,
  PAGINATION_COLORS,
  POPCONFIRM_COLORS,
  PROGRESS_COLORS,
  RADIO_COLORS,
  SELECT_COLORS,
  SLIDER_COLORS,
  SWITCH_COLORS,
  TAB_COLORS,
  TABLE_COLORS,
  UPLOAD_COLORS,
} from "@/constants/colors/AntdColors";

export const ANTD_COMPONENTS = {
  components: {
    Form: FORM_COLORS,
    Input: INPUT_COLORS,
    Notification: NOTIFICATION_COLORS,
    Pagination: PAGINATION_COLORS,
    Select: SELECT_COLORS,
    Radio: RADIO_COLORS,
    Switch: SWITCH_COLORS,
    Upload: UPLOAD_COLORS,
    Popconfirm: POPCONFIRM_COLORS,
    Progress: PROGRESS_COLORS,
    Button: BUTTON_COLORS,
    Checkbox: CHECKBOX_COLORS,
    Table: TABLE_COLORS,
    Collapse: { colorBorder: "#E6EAED" },
    Spin: { colorPrimary: "#000" },
    Slider: SLIDER_COLORS,
    DatePicker: DATE_PICKER_COLORS,
    Carousel: CAROUSEL_COLORS,
  },
};
