export const TOP_EXPERTS_CONTENT = {
  header: {
    title: "Top Experts",
    highlightWord: "Experts",
    description:
      "Our skilled and reliable experts, your most trusted partners.",
    allExpertsLink: {
      href: "./find-workers.html",
      text: "All Experts",
      iconClass: "ph-bold ph-arrow-right text-2xl !leading-none",
    },
  },

  experts: [
    {
      id: 1,
      name: "Evan Dev",
      location: "Brooklyn, NY, USA",
      badges: ["PRO"],
      priceRange: "$75 - $100/hr",
      tags: ["TOP INDEPENDENT", "AVAILABLE"],
      skills: ["Handyman", "Plumber", "+3"],
      verifiedBadgeImage: "./assets/images/verify-badge.png",
      sliderImages: [
        "./assets/images/expert_slider_img_2.png",
        "./assets/images/expert_slider_img_1.png",
        "./assets/images/expert_slider_img_3.png",
        "./assets/images/expert_slider_img_4.png",
        "./assets/images/expert_slider_img_5.png",
        "./assets/images/expert_slider_img_6.png",
        "./assets/images/expert_slider_img_2.png",
        "./assets/images/expert_slider_img_3.png",
      ],
      profileLink: "./worker-profile.html",
    },
    {
      id: 2,
      name: "Ruth Vega",
      location: "Brooklyn, NY, USA",
      badges: ["PRO"],
      priceRange: "$75 - $100/hr",
      tags: ["TOP INDEPENDENT", "AVAILABLE"],
      skills: ["Handyman", "Plumber", "+3"],
      verifiedBadgeImage: "./assets/images/verify-badge.png",
      sliderImages: [
        "./assets/images/expert_slider_img_3.png",
        "./assets/images/expert_slider_img_1.png",
        "./assets/images/expert_slider_img_2.png",
        "./assets/images/expert_slider_img_4.png",
        "./assets/images/expert_slider_img_5.png",
        "./assets/images/expert_slider_img_6.png",
        "./assets/images/expert_slider_img_2.png",
        "./assets/images/expert_slider_img_3.png",
      ],
      profileLink: "./worker-profile.html",
    },
    {
      id: 3,
      name: "Ruth Vega",
      location: "Brooklyn, NY, USA",
      badges: ["PRO"],
      priceRange: "$75 - $100/hr",
      tags: ["TOP INDEPENDENT", "AVAILABLE"],
      skills: ["Handyman", "Plumber", "+3"],
      verifiedBadgeImage: "./assets/images/verify-badge.png",
      sliderImages: [
        "./assets/images/expert_slider_img_3.png",
        "./assets/images/expert_slider_img_1.png",
        "./assets/images/expert_slider_img_2.png",
        "./assets/images/expert_slider_img_4.png",
        "./assets/images/expert_slider_img_5.png",
        "./assets/images/expert_slider_img_6.png",
        "./assets/images/expert_slider_img_2.png",
        "./assets/images/expert_slider_img_3.png",
      ],
      profileLink: "./worker-profile.html",
    },
  ],
};
